"""initial

Revision ID: 93d1ad53d144
Revises: 
Create Date: 2026-05-04 16:05:53.367240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d1ad53d144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('known_name', sa.String(length=500), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('known_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('dba', sa.String(length=500), nullable=True),
    sa.Column('duns', sa.String(length=20), nullable=True),
    sa.Column('facility_id', sa.String(length=100), nullable=True),
    sa.Column('health_authority', sa.String(length=100), nullable=True),
    sa.Column('parent_organization', sa.String(length=500), nullable=True),
    sa.Column('registered_entity', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IMPORTED', 'MAPPED', 'ACTIVE', 'FLAGGED', 'MONITORED', 'ARCHIVED', name='supplierstatus'), nullable=False),
    sa.Column('unified_score', sa.Float(), nullable=True),
    sa.Column('score_sources_available', sa.Integer(), nullable=False),
    sa.Column('score_sources_total', sa.Integer(), nullable=False),
    sa.Column('score_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orgbook_match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_duns'), 'suppliers', ['duns'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('events', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('infraction_type', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'MODERATE', 'NON_CRITICAL', name='infractionseverity'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'RESOLVED', 'ACTIVE', name='infractionstatus'), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infractions_reported_date'), 'infractions', ['reported_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infractions_reported_date'), table_name='infractions')
    op.drop_table('infractions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_suppliers_duns'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('supplier_aliases')
    # ### end Alembic commands ###
